### ISSUE TITLE
Possible code for Chapter 11

### ISSUE THREAD

**Issue by rcpacheco** [SquareBracketAssociates/LearningOOPWithPharo#10]
There is some turtle graphics code that may or may not be useful as a starting point for this chapter:  https://github.com/souravdatta/turtles.

I just mention it for you to consider if it fits your need.

**Comment by Ducasse** [comment]
I have the code 
Now I want the reader to be able to implement it at the end.
And I wanted to check if it would be working on athens.

**Comment by rcpacheco** [comment]
Ok thanks. Let me know if I can help. I will close the issue.

**Comment by Ducasse** [comment]
In fact I have LSystems and 3 chapters using a turtle. 
Now the morphic turtle I have is not nice because redrawing the background erase it. 
I tried with athens but I did not have the time to fully get somethign. 
If you succeed to have an athens window with a little turtle drawing inside it would really help me.

**Comment by rcpacheco** [comment]
I'm new to Pharo, but will see what I can do. Is a a good challenge to learn. I'll get back on this topic in a few days :)

**Comment by Ducasse** [comment]
have a look at the snow flake demo
